services:
  - type: web
    name: qontextualize-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "chrome-extension://khkgofpfbckbnllmljfkfephjonambpj,https://api.qontextualize.com"
      - key: PORT
        value: "10000"